<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="1" failures="0" skipped="0" tests="1" time="0.270" timestamp="2023-07-13T01:52:40.290542" hostname="abhishek-virtualbox"><testcase classname="" name="tests.test_allowed_file" time="0.000"><error message="collection failure">ImportError while importing test module '/home/abhishekc/Projects/SwiftAI-Bot/Yolo5/tests/test_allowed_file.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_allowed_file.py:2: in &lt;module&gt;
    from app import allowed_file, ALLOWED_EXTENSIONS
app.py:5: in &lt;module&gt;
    from detect import run
E   ImportError: cannot import name 'run' from 'detect' (/home/abhishekc/.local/lib/python3.10/site-packages/detect/__init__.py)</error></testcase></testsuite></testsuites>